version: 3
tasks:
  python:env:
    cmds:
      - uv sync --extra dev --extra github
  python:lint:
    desc: Lint Python files
    deps:
      - python:env
    cmds:
      - uv run ruff check --output-format=github --select=E9,F63,F7,F82 --target-version=py39 .
      - uv run ruff check --output-format=github --target-version=py39 .

  docker:build:
    desc: Build the container using Docker
    cmds:
      - docker build . -t smsbot:latest