version: 3
tasks:
  default:
    deps:
      - python:tests
      - python:lint

  python:tests:
    desc: Run Python tests
    cmds:
      - uv run --dev --group github pytest

  python:lint:
    desc: Lint Python files
    cmds:
      - uv run --dev ruff check --output-format=github --select=E9,F63,F7,F82 --target-version=py39 .
      - uv run --dev ruff check --output-format=github --target-version=py39 .

  docker:build:
    desc: Build the container using Docker
    cmds:
      - docker build . --build-arg PYTHON_VERSION=$(cat .python-version) -t smsbot:latest

  smsbot:run:
    desc: Run the SMSBot
    cmds:
      - uv run smsbot