---
# yaml-language-server: $schema=https://nikdoof.github.io/flux-gitops/schemas/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nikdoof
  namespace: flux-system
spec:
  interval: 4h
  url: https://nikdoof.github.io/helm-charts/
---
# yaml-language-server: $schema=https://nikdoof.github.io/flux-gitops/schemas/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: smsbot
spec:
  interval: 12h
  chart:
    spec:
      chart: common-chart
      version: 1.2.3
      sourceRef:
        kind: HelmRepository
        name: nikdoof
        namespace: flux-system
      interval: 12h
  values:
    global:
      nameOverride: smsbot
    image:
      repository: ghcr.io/nikdoof/smsbot
      tag: 0.2.0
      imagePullPolicy: IfNotPresent
    controller:
      strategy: Recreate
      annotations:
        secret.reloader.stakater.com/reload: "smsbot-secrets"
    envFrom:
      - secretRef:
          name: smsbot-secrets
    service:
      main:
        ports:
          http:
            port: 5000
    ingress:
      main:
        enabled: true
        hosts:
          - host: smsbot-webhooks.example.com
            paths:
              - path: /
                pathType: Prefix

