apiVersion: v2
appVersion: 0.0.3
description: A simple Telegram bot to receive SMS messages.
name: smsbot
version: 0.0.4
kubeVersion: ">=1.19.0-0"
keywords:
- smsbot
home: https://github.com/nikdoof/smsbot/tree/main/charts/smsbot
sources:
- https://github.com/nikdoof/smsbot
maintainers:
- name: nikdoof
  email: nikdoof@users.noreply.github.com
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.5.2
